"""Pre-draft a prompt-delta from the tuning digest — the loop's last mile, kept human-approved.

The tuning digest surfaces WHERE the model keeps getting corrected (recurring ``prev → new`` transitions
on the governed fields) and WHY (reviewer feedback notes). This turns that signal into a concrete,
reviewable STARTING POINT: a targeted, additive clarification the model proposes for the extraction
prompt's definitions. It is a **draft for a human**, never applied — writing the change still means editing
``app/extract/prompt.py``, bumping ``PROMPT_VERSION``, and re-running the eval first (CLAUDE.md §10). Drafting
runs on the LOCAL model ($0, Directive 2).

Honest guardrails travel WITH every draft (``_CAVEATS``): it optimises toward the reviewer's labels, so on
self-authored corrections it is self-grading — it earns trust only when the corrections come from an
INDEPENDENT reviewer; and it is a hypothesis to test, not a validated fix.
"""

from __future__ import annotations

import json
from typing import Any

from ..backends.interfaces import LLMBackend
from .prompt import PROMPT_VERSION
from .schema import DESIRED_OUTCOMES, EMOTIONS, SEVERITIES, TAXONOMY

# Grammar-constrained draft: a title, the additive rule to add, and why. Deliberately small — the model
# proposes ONE targeted clarification, not a prompt rewrite.
DRAFT_SCHEMA: dict[str, object] = {
    "type": "object",
    "properties": {
        "title": {"type": "string"},
        "delta": {"type": "string"},
        "rationale": {"type": "string"},
    },
    "required": ["title", "delta", "rationale"],
}

_MAX_TRANSITIONS = 5
_MAX_NOTES = 5

# Fixed, non-negotiable caveats attached to every draft (never model-generated — these are project law).
_CAVEATS: list[str] = [
    (
        "DRAFT for review — NOT applied. To ship it: edit app/extract/prompt.py, bump PROMPT_VERSION, "
        "and re-run the eval (eval/score.py) FIRST. Never ship a prompt change without re-scoring "
        "(CLAUDE.md §10)."
    ),
    (
        "Drafted from reviewer CORRECTIONS, so it optimises toward those labels. On self-authored "
        "corrections that is self-grading — it earns trust when the corrections come from an INDEPENDENT "
        "reviewer. For category the binding lever stays independent labels, not another prompt version."
    ),
    "Generated by the local model ($0) as a starting point — a hypothesis to test, not a validated fix.",
]


def _based_on(transitions: list[dict[str, Any]], notes: list[dict[str, Any]]) -> list[str]:
    """The exact signal the draft was grounded in — so a reviewer can trace the proposal to its evidence."""
    out = [f"{t['field_path']}: {t['from']} → {t['to']} (×{t['count']})" for t in transitions]
    out += [f"feedback [{n['verdict']}]: {n['comment']}" for n in notes]
    return out


def build_draft_prompt(transitions: list[dict[str, Any]], notes: list[dict[str, Any]]) -> str:
    """The instruction the local model drafts against: the fixed vocabularies + the recurring corrections
    and feedback, asking for ONE additive disambiguation rule (not a rewrite), grounded in the signal.
    """
    lines = [
        (
            "You improve a customer-intake EXTRACTION prompt for a local LLM that labels complaints into "
            "a FIXED governed core. Human reviewers keep CORRECTING its labels. Draft ONE targeted, "
            "ADDITIVE clarification that would reduce these SPECIFIC mistakes without over-firing."
        ),
        "",
        f"category vocabulary: {', '.join(TAXONOMY)}",
        f"desired_outcome vocabulary: {', '.join(DESIRED_OUTCOMES)}",
        f"emotion vocabulary: {', '.join(EMOTIONS)}",
        f"severity vocabulary: {', '.join(SEVERITIES)}",
    ]
    if transitions:
        lines += [
            "",
            "Recurring reviewer corrections (model predicted LEFT, a human changed it to RIGHT):",
        ]
        lines += [
            f"  - {t['field_path']}: {t['from']} -> {t['to']} ({t['count']}x)" for t in transitions
        ]
    if notes:
        lines += ["", "Reviewer feedback notes:"]
        lines += [f"  - [{n['verdict']}] {n['comment']}" for n in notes]
    lines += [
        "",
        "Return JSON {title, delta, rationale}:",
        "- title: one line naming the change.",
        (
            "- delta: the EXACT 1-4 sentence rule to ADD to the prompt's definitions — a concrete "
            "disambiguation (when to prefer RIGHT over LEFT, and the distinguishing test). Additive "
            "only; do NOT rewrite the whole prompt. Stay strictly inside the vocabularies above."
        ),
        "- rationale: why this fixes the observed corrections without over-firing.",
    ]
    return "\n".join(lines)


async def draft_prompt_delta(digest: dict[str, Any], *, llm: LLMBackend) -> dict[str, Any]:
    """Draft a reviewable prompt-delta from a tuning digest. Always returns a dict carrying the honest
    caveats; ``draft`` is None (with a ``reason``) when there is no signal yet or the model output was
    unusable — never raises on a bad model response, and never applies anything."""
    transitions = list(digest.get("correction_transitions") or [])[:_MAX_TRANSITIONS]
    notes = [n for n in (digest.get("feedback", {}) or {}).get("recent", []) if n.get("comment")][
        :_MAX_NOTES
    ]
    based_on = _based_on(transitions, notes)

    if not transitions and not notes:
        return {
            "draft": None,
            "reason": "Not enough signal yet — a draft needs recurring corrections or feedback notes.",
            "based_on": [],
            "caveats": _CAVEATS,
        }

    raw = await llm.complete(build_draft_prompt(transitions, notes), schema=DRAFT_SCHEMA)
    try:
        obj = json.loads(raw)
        if not isinstance(obj, dict):
            raise TypeError("draft output was not a JSON object")
    except (json.JSONDecodeError, TypeError):
        return {
            "draft": None,
            "reason": "The local model didn't return a usable draft — try again.",
            "based_on": based_on,
            "caveats": _CAVEATS,
        }

    fields = sorted({str(t["field_path"]) for t in transitions}) or ["governed core"]
    target = f"app/extract/prompt.py ({PROMPT_VERSION}) — {', '.join(fields)} definitions"
    return {
        "draft": {
            "title": str(obj.get("title", "")).strip(),
            "delta": str(obj.get("delta", "")).strip(),
            "rationale": str(obj.get("rationale", "")).strip(),
            "target": target,
        },
        "based_on": based_on,
        "caveats": _CAVEATS,
    }
